name: 'Terramate'
description: 'Terramate'
inputs:
  version:
    description: 'Terramate version'
    required: false
    default: latest
  use_wrapper:
    description: 'Use wrapper'
    required: false
    default: "true"
outputs:
  stdout:
    description: "Stdout"
    value: ${{ steps.run.outputs.stdout }}
  stderr:
    description: "Stderr"
    value: ${{ steps.run.outputs.stderr }}
  exitcode:
    description: "Exit code"
    value: ${{ steps.run.outputs.exitcode }}
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - id: run
      run: install.sh
      shell: bash
      env:
        TM_VERSION:  ${{inputs.version}}
        USE_WRAPPER: ${{inputs.use_wrapper}}
