name: 'Terramate'
description: 'Terramate'
inputs:
  version:
    description: 'Terramate version'
    required: false
  use_wrapper:
    description: 'Use wrapper'
    required: false
    default: "true"
  cloud_organization:
    description: 'Terramate Cloud organization to use'
    required: false
runs:
  using: "composite"
  steps:
    - name: Adding action_path to GITHUB_PATH
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: Installing Terramate
      run: install.sh
      shell: bash
      env:
        TM_VERSION:  ${{inputs.version}}
        USE_WRAPPER: ${{inputs.use_wrapper}}
    - name: Configuring Terramate execution environment
      run: echo "TM_CLOUD_ORGANIZATION=${{inputs.cloud_organization}}" >> $GITHUB_ENV
      if: ${{ inputs.cloud_organization != '' }}
      shell: bash
